#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Print i as the 9th item
var1="Best School"
var2="Hi"
i="1"

while [ $i -lt 11 ]; do
	if [ $i -eq 10 ]; then
		echo "$var2"
	fi
	echo "$var1"
	((i++))
done
